language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "3.5"

before_install:
  - git submodule update --init --recursive
  - pip install flake8

install:
  - pip install -r contrib/requirements.txt

script:
  - flake8 .

git:
  submodules: false

notifications:
  irc:
    channels:
      - "ircs:irc.hackint.net:9999#bytespeicher-testing"
    skip_join: true
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Mehr zum Test: %{build_url}"
