python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - git submodule update --init --recursive

install: true

git:
  submodules: false

notifications:
  irc:
    channels:
      - "ircs:irc.hackint.net:9999#bytespeicher-testing"
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Mehr zum Test: %{build_url}"
