language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - git submodule update --init --recursive
  - pip install flake8

install:
  - pip install -r contrib/requirements.txt

script:
  - flake8 .

git:
  submodules: false

notifications:
  irc:
    channels:
      - "ircs:irc.hackint.net:9999#bytespeicher-testing"
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Mehr zum Test: %{build_url}"
